"""List of API endpoints for OPEN XBL."""

API_PATH = {
    "account": "/account",
    "account_xuid": "/account/{xuid}",
    "achievements": "/achievements",
    "achievements_game": "/achievements/title/{titleId}",
    "achievements_game_xuid": "/achievements/player/{xuid}/title/{titleid}",
    "achievements_history": "/achievements/{titleId}",
    "achievements_xuid": "/achievements/player/{xuid}",
    "activity_feed": "/activity/feed",
    "activity_history": "/activity/history",
    "alerts": "/alerts",
    "club_recommendations": "/clubs/recommendations",
    "club_summary": "/clubs/{clubId}",
    "clubs_create": "/clubs/create",
    "clubs_owned": "/clubs/owned",
    "clubs_reserve": "/clubs/reserve",
    "clubs_search": "/clubs/find",
    "conversation_requests": "/conversations/requests",
    "conversations": "/conversations",
    "conversations_xuid": "/conversations/{xuid}",
    "dvr_gameclips": "/dvr/gameclips",
    "dvr_gameclips_delete": "/dvr/gameclips/delete/{{GameContentID}}",
    "dvr_screenshots": "/dvr/screenshots",
    "friends": "/friends",
    "friends_add": "/friends/add/{xuid}",
    "friends_favorite": "/friends/favorite",
    "friends_favorite_remove": "/friends/favorite/remove",
    "friends_remove": "/friends/remove/{xuid}",
    "friends_search": "/friends/search",
    "friends_xuid": "/friends",
    "generate_gamertag": "/generate/gamertag",
    "group": "/group",
    "group_create": "/group/create",
    "group_invite": "/group/invite/voice",
    "group_kick": "/group/kick",
    "group_leave": "/group/leave",
    "group_messages": "/group/messages/{group id}",
    "group_rename": "/group/rename",
    "group_send": "/group/send",
    "group_summary": "/group/summary/{group id}",
    "party": "/party",
    "party_invite": "/party/invite/{sessionId/scid}",
    "player_summary": "/player/summary",
    "presence": "/presence",
    "presence_xuid": "/{xuid}/presence",
    "recent_players": "/recent-players",
    "stats_game": "/achievements/stats/{titleId}"
}
